---
title: "logboek Jorick"
author: "Jorick Baron"
date: "9/14/2022"
output: pdf_document
---

## Dag 1

*14-9-2022*

-   created git.

-   selected dataset: <https://www.kaggle.com/datasets/johnjdavisiv/urinary-biomarkers-for-pancreatic-cancer?select=Debernardi+et+al+2020+data.csv>

-   started EDA.

-   finished codebook.

## Dag 2

*16-9-2022*

-   did assignment reproducible research

-   research question: Can a model be trained using machine learning techniques to detect if a person has pancreatic cancer using data from a urine sample?

-   made sure the data loaded correctly.

## Dag 3

*19-9-2022*

-   checked if the NAs of columns "stage" and "benign_sample_diagnosis" where correct.

-   checked if the NAs of columns "plasma_CA19_9" and "REG1A" where correct.

## Dag 4

*20-9-2022*

-   explored distribution of data using box-plots.

-   explored distribution of grouped data using box-plots.

-   made a second dataframe containing log transformed values.

## Dag 5

22-9-2022

-   calculated skewness of untransformed data.

-   created qq_plots of transformed data.

## Dag 6

*23-9-2022*

-   processed feedback to alter research question to: "how accurate can a model be trained to detect the difficult to diagnose pancreatic cancer utilising a patient's urine sample?"

-   will create new dataset with only the relevant columns dropping: sample_id, patient_cohort, stage, benign_sample_diagnosis and plasma_CA19_9 due to it not being from urine.

-   fixed log transformation.

-   created heat-map.

## Dag 7

*26-9-2022*

-   looked at class distribution.

-   added new column containing if patient had cancer lumping the control and non cancer patients together.

-   explored for significant differences in attributes using t tests.

-   added more text and structure

-   fixed grammar

## Dag 8

*27-9-2022*

-   evaluated EDA of Wouter Z.

-   finalized the data set .

-   loaded data in weka and found that SimpleLogistic can predict with a 83.5% accuracy.
